name: Makefile Tests

on:
  push:
    branches: [ "master" "beta" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Verify Bash Specs
      run: make -C tests check
