name: Makefile Tests

on:
  push:
    branches: [ "master", "beta" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Verify Bash Specs (makefile)
      run: make -C tests check

    - name: Verify Bash Specs (shell runner)
      run: tests/_run.sh
